config/routes.rb
Kehou::Application.routes.draw do
  scope '/users/:user_id/' do
    resources :favorites, shallow: true
    resources :groups, shallow: true do
      resources :messages, shallow: true do
        get :reply, to: 'messages#reply'
      end
      resources :shared_files, shallow: true
    end
    resource :group_members, shallow: true
    resources :assignments, shallow: true do
      get :finished, to: 'assignments#finished_students'
      get :unfinished, to: 'assignments#unfinished_students'
    end

    scope '/assignments/:assignment_id/' do
      resources :assignment_attempts, shallow: true do
        post :post_answer
      end
    end

    get 'assignments/new/choose', :to => 'assignments#choose_practice'

    constraints lambda {|req| User.find(req['user_id']).usertype == :teacher} do
      root :to => "teacher#home", :as => :person_home
      get :home, :to => "teacher#home"
      get :exams, :to => "teacher#exams"
    end

    constraints lambda {|req| User.find(req['user_id']).usertype == :student} do
      root :to => "student#home", :as => :person_home
    end

    constraints lambda {|req| User.find(req['user_id']).usertype == :parent} do
      root :to => "parent#home", :as => :person_home
    end
  end

  resources :profiles

  get "clearsky/index_grade"
  get "clearsky/index_all"
  get "clearsky/landing"
  match '/clearsky/book/:id' => 'clearsky#show_book'
  match '/clearsky/books/:grade' => 'clearsky#show_book_by_grade'
  match "/clearsky/tongbu/:grade/" => 'clearsky#show_tongbu'
  match "/clearsky/tongbu/:grade/:unit" => 'clearsky#do_tongbu'
  match "/clearsky/exam/:id" => 'clearsky#show_practice'
  match "/clearsky/search" => 'clearsky#search'

  match "/explain/displayxml.do" => 'clearsky#displayxml'
  match "/examxml/:id" => 'clearsky#examxml'

  match "/404", :to => "errors#not_found"
  match "/422", :to => "errors#server_error"
  match "/500", :to => "errors#server_error"

  match '/home'  => "kehou#home"
  match '/home2'  => "kehou#home"
  match '/coursewares/:id' => 'kehou#courseware'
  match '/grades/:grade' => 'kehou#grade'
  match '/materials/:id' => 'kehou#material'
  match '/materials/:id/download' => 'kehou#material_download'
  match '/grades/:grade/:category' => 'kehou#grade_category'
  match '/search' => 'kehou#search'
  match '/about' => 'kehou#about'
  match '/comments' => 'kehou#comments'
  match '/contacts' => 'kehou#contacts'
  match '/signed_in_forum' => 'kehou#signed_in_forum'
  match '/logout_redirect' => 'kehou#logout_redirect'

  resources :group_member_invitations do
    collection do
      get :join
      get :regularize
      put :join, to: :active
    end
  end

  scope "/admin" do
    resources :coursewares, :user_type => :admin
  end

  resources :courseware_materials

  match "/update_captcha" => 'simple_captcha#update_captcha'

  get "admin/home"

  get "admin/questions"

  get "admin/exams"

  get "admin/profile"

  devise_for :users, :path => "/", :controllers => { :sessions => "users/sessions", :registrations => "users/registrations" },
    :path_names => {
        :sign_in => 'login',
        :sign_out => 'logout',
        :registration => 'register',
        :sign_up => 'new' }

  devise_for :admins, :path => "/admin", :controllers => { :sessions => "admins/sessions" },
    :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  root :to => 'kehou#home'

  match "/admin" => 'admin#home'

end

app/models/group_member_invitation.rb
# -*- encoding : utf-8 -*-
class GroupMemberInvitation < ActiveRecord::Base
  attr_accessible :email, :name, :group_id, :user_id, :token, :usertype
  attr_accessor :usertype
  
  belongs_to :group
  belongs_to :user

  
  def member
    user.group_members.find_by_group_id(self.group_id)
  end
    
  validates_presence_of :email, :name, :group
  
  before_create do 
    self.token = SecureRandom.urlsafe_base64(32)
    
    # 关联User，如果User不存在，创建虚拟User
    unless user = User.find_by_email(email)
      user = User.create! virtual: true, email: email, name: name, usertype: usertype,
        password: SecureRandom.urlsafe_base64(32)
    end
    
    self.user_id = user.id
    
    # 创建没有确认加入的member      
    GroupMember.create! group_id: group_id, user_id: user_id, name: name
        
  end
  
  after_create do 
    GroupMailer.invite(self).deliver
  end
end

app/controllers/group_member_invitations_controller.rb
# -*- encoding : utf-8 -*-
class GroupMemberInvitationsController < ApplicationController
  include SimpleCaptcha::ControllerHelpers
  
  # 如果邀请函不存在或者已经被使用过，则跳转
  def redirect_if_invitation_invalid token
    invitation = GroupMemberInvitation.find_by_token(token)
    if !invitation or invitation.member.joined_at
      # 可跳转到一个提示邀请函无效的页面
      redirect_to root_path
      nil
    else
      invitation
    end
  end
  
  # 通过邮件邀请加入
  def join
    return unless invitation = redirect_if_invitation_invalid(params[:token])
    
    user = invitation.user
    if user.virtual?
      redirect_to action: "regularize", token: params[:token]
    else
      sign_in user, :bypass => true
      invitation.member.update_attribute :joined_at, Time.now
      
      # TODO 跳转到小组页面
      redirect_to root_path
    end
  end
  
  def regularize
    return unless invitation = redirect_if_invitation_invalid(params[:token])
    
    @user = invitation.user
    @user.name = ""
  end
  
  def active
    return unless invitation = redirect_if_invitation_invalid(params[:token])
    
    @user = invitation.user
    @user.assign_attributes params[:user]
    @user.virtual = false
    unless simple_captcha_valid?
      flash[:error] = "验证码不正确"
      return render action: 'regularize'
    end
    if @user.save
      sign_in @user, :bypass => true
         
      invitation.member.update_attribute :joined_at, Time.now
      
      session[:group_member_invitation] = nil
      
      # TODO 跳转到当前小组的主页
      # invication = session[:group_member_invitation]
      # group = invication.group
      redirect_to root_path
    else  
      render action: "regularize" 
    end
  end
end

app/views/group_member_invitations/regularize.html.erb
<div class="container login">
  <div class="header">
    <div class="content">
      <div class="logo"> <%= image_tag "logo_big.png" %> </div>
    </div>
  </div>
  <div class="mainbody">
    <div class="content">
      <%= form_for @user, url: join_group_member_invitations_path, method: :put,
        html: {class: 'activeform'} do |f|%>
        <%= hidden_field_tag :token, params[:token] %>
        <h2>激活账号</h2>
        <h3><%= @user.email %></h3>
        <%= f.text_field :name, :class => 'input', :addclass=>'lg_rname', :validate => 'required',
          placeholder: "姓名(必填)", autofocus: true %>
        <%= f.password_field :password, class: 'input', validate: 'required pwd', placeholder: '密码(必填)' %>
        <%= f.password_field :password_confirmation, class: 'input', validate: 'required pwd', 
          placeholder: '确认密码(必填)' %>
          
          <%= show_simple_captcha :label => '验证码' %>
        <div class="space"></div>
        <%= f.submit "激活账号", class: 'btn btn1 btnlogin' %>
        <%= render "shared/error_msg", resource: @user %>
    <% end %>
      
    </div>
  </div>
  <div class="footer">
    <div class="content">
      <p>
        <a href="#">网校首页</a> |
        <a href="#">关于我们</a> |
        <a href="#">投诉与建议</a> |
        <a href="#">联系我们</a>
      </p>
      <p>
        版权所有 &copy; 51KeHou.com 未经许可 严禁复制    建议使用1024X768分辨率浏览本站 <br />
        沪ICP备1020370538号 
      </p>
    </div>
  </div>
  <div class="space"></div>
</div>