config/routes.rb
Kehou::Application.routes.draw do
  scope '/users/:user_id/' do
    resources :favorites, shallow: true
    resources :groups, shallow: true do
      resources :messages, shallow: true do
        get :reply, to: 'messages#reply'
      end
      resources :shared_files, shallow: true
    end
    resource :group_members, shallow: true
    resources :assignments, shallow: true do
      get :finished, to: 'assignments#finished_students'
      get :unfinished, to: 'assignments#unfinished_students'
    end

    scope '/assignments/:assignment_id/' do
      resources :assignment_attempts, shallow: true do
        post :post_answer
      end
    end

    get 'assignments/new/choose', :to => 'assignments#choose_practice'

    constraints lambda {|req| User.find(req['user_id']).usertype == :teacher} do
      root :to => "teacher#home", :as => :person_home
      get :home, :to => "teacher#home"
      get :exams, :to => "teacher#exams"
    end

    constraints lambda {|req| User.find(req['user_id']).usertype == :student} do
      root :to => "student#home", :as => :person_home
    end

    constraints lambda {|req| User.find(req['user_id']).usertype == :parent} do
      root :to => "parent#home", :as => :person_home
    end
  end

  resources :profiles

  get "clearsky/index_grade"
  get "clearsky/index_all"
  get "clearsky/landing"
  match '/clearsky/book/:id' => 'clearsky#show_book'
  match '/clearsky/books/:grade' => 'clearsky#show_book_by_grade'
  match "/clearsky/tongbu/:grade/" => 'clearsky#show_tongbu'
  match "/clearsky/tongbu/:grade/:unit" => 'clearsky#do_tongbu'
  match "/clearsky/exam/:id" => 'clearsky#show_practice'
  match "/clearsky/search" => 'clearsky#search'

  match "/explain/displayxml.do" => 'clearsky#displayxml'
  match "/examxml/:id" => 'clearsky#examxml'

  match "/404", :to => "errors#not_found"
  match "/422", :to => "errors#server_error"
  match "/500", :to => "errors#server_error"

  match '/home'  => "kehou#home"
  match '/home2'  => "kehou#home"
  match '/coursewares/:id' => 'kehou#courseware'
  match '/grades/:grade' => 'kehou#grade'
  match '/materials/:id' => 'kehou#material'
  match '/materials/:id/download' => 'kehou#material_download'
  match '/grades/:grade/:category' => 'kehou#grade_category'
  match '/search' => 'kehou#search'
  match '/about' => 'kehou#about'
  match '/comments' => 'kehou#comments'
  match '/contacts' => 'kehou#contacts'
  match '/signed_in_forum' => 'kehou#signed_in_forum'
  match '/logout_redirect' => 'kehou#logout_redirect'

  resources :group_member_invitations do
    collection do
      get :join
      get :regularize
      put :join, to: :active
    end
  end

  scope "/admin" do
    resources :coursewares, :user_type => :admin
  end

  resources :courseware_materials

  match "/update_captcha" => 'simple_captcha#update_captcha'

  get "admin/home"

  get "admin/questions"

  get "admin/exams"

  get "admin/profile"

  devise_for :users, :path => "/", :controllers => { :sessions => "users/sessions", :registrations => "users/registrations" },
    :path_names => {
        :sign_in => 'login',
        :sign_out => 'logout',
        :registration => 'register',
        :sign_up => 'new' }

  devise_for :admins, :path => "/admin", :controllers => { :sessions => "admins/sessions" },
    :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  root :to => 'kehou#home'

  match "/admin" => 'admin#home'

end

app/models/user.rb
# -*- encoding : utf-8 -*-

class User < ActiveRecord::Base
  USERTYPES = ['teacher', 'student', 'parent']

  has_attached_file :avatar, :styles => { :thumb => "48x48>", :medium => "100x100>" }, :default_url => "face.jpg"

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :timeoutable

  symbolize :usertype, :in => {
    teacher: '老师',
    student: '学生',
    parent: '家长'
  }, :scopes => true

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :usertype, :email, :password, :password_confirmation, :remember_me, :im, :phone, :avatar, :virtual, :flags
  # attr_accessible :title, :body

  validates :name, :uniqueness => true, :presence => true

  has_many :group_members, dependent: :destroy
  has_many :groups, through: :group_members, :uniq => true
  has_many :assignments, foreign_key: :creator_id, order: 'updated_at DESC'
  has_one :profile
  has_many :favorites
  has_many :assignment_attempts, foreign_key: :participant_id

  def children_assignments
    if usertype == :parent
      group_members.map{|gm| gm.child.user}.uniq.map{|u| u.assigned_assignments}.flatten + assignments.where({assigned_user_id: child(groups.first.id) })
    else
      []
    end
  end

  # todo: 限制是一个群组内家长只能和一个学生对应
  def child(group_id)
    if usertype == :parent
      group_members.select{|g| g.group_id == group_id}.map{|gm| gm.child.user}.first
    else
      nil
    end
  end

  def assigned_assignments
    if usertype == :student
      groups.map{|g| g.assignments}.flatten + Assignment.where({assigned_user_id: id})
    else
      []
    end
  end

  def students
    if usertype == :teacher
      groups.map{|g| g.members.where(usertype: :student).map(&:user) }.flatten
    else
      []
    end
  end

  def final_avatar
    if profile && profile.avatar?
      profile.avatar
    else
      avatar
    end
  end

  after_create :create_forum_account
  after_update :update_forum_account
  after_destroy :destroy_forum_account

  def User.execute_sql_on_forum(*sql_array)
    ForumAccount.connection.execute(ActiveRecord::Base.send(:sanitize_sql_array, sql_array))
  end

  def User.all_forum_users
    execute_sql_on_forum("SELECT email FROM `ultrax`.`pre_common_member`").collect {|x| x[0]}
  end

  def create_forum_account
    return if !password

    if User.execute_sql_on_forum("SELECT count(*) FROM `ultrax`.`pre_ucenter_members` WHERE email=?;", email).first.first > 0
      update_forum_account
    else
      salt = Random.rand.to_s.last(6)
      passwd_md5 = Digest::MD5.hexdigest(Digest::MD5.hexdigest(password) + salt)
      regdate = DateTime.now.to_i
      User.execute_sql_on_forum("INSERT INTO `ultrax`.`pre_ucenter_members`(username, password, email, regdate, salt) VALUES (?,?,?,?,?);",
                            name, passwd_md5, email, regdate, salt)
      User.execute_sql_on_forum("INSERT INTO `ultrax`.`pre_common_member`(username, password, email, regdate, groupid, credits) VALUES (?,?,?,?,?,?);",
                            name, passwd_md5, email, regdate, 10, 2)
      uid = User.execute_sql_on_forum("SELECT uid FROM `ultrax`.`pre_common_member` WHERE email=?", email).first
      User.execute_sql_on_forum("INSERT INTO `ultrax`.`pre_common_member_count`(uid) VALUES (?);", uid)
    end
  end

  def update_forum_account
    return if !password
    forum_user = User.execute_sql_on_forum("SELECT username, password, salt FROM `ultrax`.`pre_ucenter_members` WHERE email=?;", email).first
    if forum_user
      passwd_md5 = Digest::MD5.hexdigest(Digest::MD5.hexdigest(password) + forum_user[2])
      if forum_user[1] != passwd_md5 or forum_user[0] != name
        User.execute_sql_on_forum("UPDATE `ultrax`.`pre_ucenter_members` SET username=?, password=? WHERE email=?;",
                              name, passwd_md5, email)
        User.execute_sql_on_forum("UPDATE `ultrax`.`pre_common_member` SET username=?, password=? WHERE email=?;",
                              name, passwd_md5, email)
      end
    else
      create_forum_account
    end
  end

  def destroy_forum_account
    uid = User.execute_sql_on_forum("SELECT uid FROM `ultrax`.`pre_common_member` WHERE email=?", email).first
    User.execute_sql_on_forum("DELETE FROM `ultrax`.`pre_ucenter_members` WHERE email=?;", email)
    User.execute_sql_on_forum("DELETE FROM `ultrax`.`pre_common_member` WHERE email=?;", email)
    User.execute_sql_on_forum("DELETE FROM `ultrax`.`pre_common_member_count` WHERE uid=?", uid)
  end

end

app/controllers/users/registrations_controller.rb
# -*- encoding : utf-8 -*-
class Users::RegistrationsController < Devise::RegistrationsController
  skip_before_filter :require_no_authentication, :only => [:new]
    
  include SimpleCaptcha::ControllerHelpers

  def new
    if current_user
      #redirect_to root_path
      redirect_to person_home_path({user_id: current_user.id})
    else
      super
    end
  end
  
  def create 
    if simple_captcha_valid?
      # 如果用户注册的邮箱已经存在虚拟用户，那么直接对该虚拟用户进行update操作
      if self.resource = User.find_by_email_and_virtual(params[:user][:email], true)
        # 用户已经存在关系，不允许修改usertype
        params[:user][:usertype] = self.resource.usertype
                
        if self.resource.update_with_password params[:user]
          sign_in self.resource, :bypass => true
          redirect_to after_sign_in_path_for self.resource
        else
          clean_up_passwords self.resource
          respond_with_navigational(self.resource) { render "new" }
        end
      else
        super
      end

      if user_signed_in?
        session[:require_sign_in_forum] = true
        session[:password] = params[:user][:password]
      end
    else
      build_resource
      clean_up_passwords(resource)
      flash[:error] = "验证码不正确"
      respond_with_navigational(resource) { render :new }
    end
  end  
end

app/controllers/users/sessions_controller.rb
# -*- encoding : utf-8 -*-
class Users::SessionsController < Devise::SessionsController
  skip_before_filter :require_no_authentication, :only => [:new]
    
  include SimpleCaptcha::ControllerHelpers

  def new
    if params[:book_id]
      session[:book_id] = params[:book_id]
    end
    if current_user
      #redirect_to root_path
      redirect_to person_home_path({user_id: current_user.id})
    else
      super
    end
  end
  
  def create
    if Rails.env.test? || simple_captcha_valid?
      super
      if user_signed_in?
        session[:require_sign_in_forum] = true
        session[:password] = params[:user][:password]
      end
    else
      build_resource
      clean_up_passwords(resource)
      flash[:error] = "验证码不正确"
      respond_with_navigational(resource) { render :new }
    end
  end
  
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
  
  def after_sign_in_path_for(resource_or_scope)
    person_home_path({user_id: current_user.id})
    #root_path
    # case resource_or_scope.usertype
    #   when 'teacher' ; "/teacher"
    #   when 'student' ; "/student"
    #   when 'parent' ;  "/parent"
    #   else root_path
    # end
  end
  
end

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_login_register.html.erb
<script language="javascript">
</script>

<div class="container login">
	<div class="header">
		<div class="content">
			<div class="logo"><%= image_tag "logo_big.png" %></div>
		</div>
	</div>
	<div class="mainbody">
		<div class="content">
			<div class="tabs">
				<div class="tab<%= ' on' if type == 'login'-%>">用<br>户<br>登<br>录</div>
				<div class="tab<%= ' on' if type == 'register'-%>">快<br>速<br>注<br>册</div>
				<!--<div class="tab<%= ' on' if type == 'forgot_password'-%>">忘<br>记<br>密<br>码</div>-->
			</div>			
			<%= form_for(resource, :as => resource_name, :url => session_path(resource_name), 
					:html => { :id => 'loginform', :class => 'loginform', :style => ('display:none' if type != 'login') }) do |f| %>
				<%= f.email_field :email, :autofocus => true,:id =>"email_input", :class => 'input finput lg_email', :addclass=>'lg_email' %>
				<%= f.password_field :password, :id=>"pwd_input", :class => 'input finput lg_lpwd', :addclass=>'lg_lpwd' %>
				<%= show_simple_captcha :label => '验证码' %>
				<div class="space"></div>
				<%= f.submit "用户登录", :class => 'btn btn1 btnlogin' %>
				<!--
				<p class="loginas"> 你也可以 <br /><a href="#"><%= image_tag "qq_login.gif" %></a></p>
				-->
				<%= render "shared/error_msg" %>
			<% end %>
			

			<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name),
					:html => { :class => "registerform", method: :post, :id => "registerform", :style => ('display:none' if type != 'register') }) do |f| %>
				<div class="roles" style="display:none;">
					<div class="role teacher"><input type="button" cdata='teacher' value="我是老师" /></div>
					<div class="role student"><input type="button" cdata='student' value="我是学生" /></div>
					<div class="role parent"><input type="button" cdata='parent' value="我是家长" /></div>
					<div class="space"></div>
				</div>
				<%= f.select :usertype, User.get_usertype_values, :selected => resource.usertype, style: 'display: none' %>
				<%= f.text_field :name, :id =>"rname_input", :class => 'input finput lg_rname', :addclass=>'lg_rname', :validate => 'required' %>
				<%= f.email_field :email, :id =>"email_input", :class => 'input finput lg_email', :addclass=>'lg_email', :validate => 'required' %>
				<%= f.password_field :password, :id =>"pwd_input", :class => 'input finput lg_pwd', :addclass=>'lg_pwd', :validate => 'required' %>
				<%= f.password_field :password_confirmation, :id =>"cpwd_input", :class => 'input finput lg_cpwd', :addclass=>'lg_cpwd', :validate => 'required'%>
				
				<%= show_simple_captcha :label => '验证码' %>
				<div class="space"></div>
  
 				<div><%= f.submit "免费注册", :class => 'btn btn1 btnlogin' %></div>
 				<%= render "shared/error_msg" %>
		<% end %>
			
			<%= form_for(resource, :as => resource_name, :url => new_password_path(resource_name),
				:html => { :class => "forgotform", :id => "forgotform", :style => ('display:none' if type != 'forgot_password')}) do |f| %>
				<p>方式一:</p>
				<input type="text" class="input finput lg_email2" addclass="lg_email2" /> 
				
				<p>方式二: </p>
				<input type="text" class="input finput lg_phone" addclass="lg_phone" />
				
				<div class="space line"></div>
				
				<%= show_simple_captcha :label => '验证码' %>
				<div class="space"></div>
				<input type="button" value="获取密码" class="btn btn1 btnlogin"  onclick="window.location='my_home_student.html'" />
				<%= render "shared/error_msg" %>
			<% end %>
		</div>
	</div>
	<div class="footer">
		<div class="content">
			<p></p>
			<p>
			</p>
			<p>
				版权所有 &copy; 51KeHou.com 未经许可 严禁复制    建议使用1024X768分辨率浏览本站 <br />
				沪ICP备1020370538号 
				<script language="javascript" src="http://count9.51yes.com/click.aspx?id=94528190&amp;logo=9" charset="gb2312"></script> 
				<script type="text/javascript"> 
				var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
				document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F150ae92ac15227655564f79707f8fc65' type='text/javascript'%3E%3C/script%3E"));
				</script>
			</p>
		</div>
	</div>
	<div class="space"></div>
</div>
<script language="javascript">
// tabs
$(".tabs .tab").bind("click", function(){
	var in_ = $(".tabs .tab").index(this);
	$(".tabs .tab").removeClass("on");
	$(this).addClass("on");
	$("form").hide();
	$("form:eq("+in_+")").show();
});
$(".roles input").bind("click", function(){
	$(".roles .role").removeClass("on");
	$(this).parent().addClass("on");
	var ind = $(".roles .role").index($(this).parent());
	$("#user_usertype option:eq("+ind+")").attr("selected", "selected");
});

$(document).ready(function() {
	var selected_usertype = $("#user_usertype").hide().val();
	$(".roles input[cdata='" + selected_usertype + "']").click();
	$(".finput").focus().blur();
});
// login input on focus/blur
$(".finput").on("focus", function(){
				$(this).removeClass($(this).attr("addclass"));
			})
			.on("change keyup mouseups blur", function(ev){
				if (ev.type != "blur")
				{
					$(this).parent().removeClass("field_with_errors");
				}
				var input_list = $(".finput");
				for(var a=0; a<input_list.length; a++)
				{
					if($(input_list[a]).val() == "") {
						$(input_list[a]).addClass($(input_list[a]).attr("addclass"));
					}
					else
					{
						$(input_list[a]).removeClass($(input_list[a]).attr("addclass"));
					}
				}
			});
</script>