config/routes.rb
Kehou::Application.routes.draw do
  scope '/users/:user_id/' do
    resources :favorites, shallow: true
    resources :groups, shallow: true do
      resources :messages, shallow: true do
        get :reply, to: 'messages#reply'
      end
      resources :shared_files, shallow: true
    end
    resource :group_members, shallow: true
    resources :assignments, shallow: true do
      get :finished, to: 'assignments#finished_students'
      get :unfinished, to: 'assignments#unfinished_students'
    end

    scope '/assignments/:assignment_id/' do
      resources :assignment_attempts, shallow: true do
        post :post_answer
      end
    end

    get 'assignments/new/choose', :to => 'assignments#choose_practice'

    constraints lambda {|req| User.find(req['user_id']).usertype == :teacher} do
      root :to => "teacher#home", :as => :person_home
      get :home, :to => "teacher#home"
      get :exams, :to => "teacher#exams"
    end

    constraints lambda {|req| User.find(req['user_id']).usertype == :student} do
      root :to => "student#home", :as => :person_home
    end

    constraints lambda {|req| User.find(req['user_id']).usertype == :parent} do
      root :to => "parent#home", :as => :person_home
    end
  end

  resources :profiles

  get "clearsky/index_grade"
  get "clearsky/index_all"
  get "clearsky/landing"
  match '/clearsky/book/:id' => 'clearsky#show_book'
  match '/clearsky/books/:grade' => 'clearsky#show_book_by_grade'
  match "/clearsky/tongbu/:grade/" => 'clearsky#show_tongbu'
  match "/clearsky/tongbu/:grade/:unit" => 'clearsky#do_tongbu'
  match "/clearsky/exam/:id" => 'clearsky#show_practice'
  match "/clearsky/search" => 'clearsky#search'

  match "/explain/displayxml.do" => 'clearsky#displayxml'
  match "/examxml/:id" => 'clearsky#examxml'

  match "/404", :to => "errors#not_found"
  match "/422", :to => "errors#server_error"
  match "/500", :to => "errors#server_error"

  match '/home'  => "kehou#home"
  match '/home2'  => "kehou#home"
  match '/coursewares/:id' => 'kehou#courseware'
  match '/grades/:grade' => 'kehou#grade'
  match '/materials/:id' => 'kehou#material'
  match '/materials/:id/download' => 'kehou#material_download'
  match '/grades/:grade/:category' => 'kehou#grade_category'
  match '/search' => 'kehou#search'
  match '/about' => 'kehou#about'
  match '/comments' => 'kehou#comments'
  match '/contacts' => 'kehou#contacts'
  match '/signed_in_forum' => 'kehou#signed_in_forum'
  match '/logout_redirect' => 'kehou#logout_redirect'

  resources :group_member_invitations do
    collection do
      get :join
      get :regularize
      put :join, to: :active
    end
  end

  scope "/admin" do
    resources :coursewares, :user_type => :admin
  end

  resources :courseware_materials

  match "/update_captcha" => 'simple_captcha#update_captcha'

  get "admin/home"

  get "admin/questions"

  get "admin/exams"

  get "admin/profile"

  devise_for :users, :path => "/", :controllers => { :sessions => "users/sessions", :registrations => "users/registrations" },
    :path_names => {
        :sign_in => 'login',
        :sign_out => 'logout',
        :registration => 'register',
        :sign_up => 'new' }

  devise_for :admins, :path => "/admin", :controllers => { :sessions => "admins/sessions" },
    :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  root :to => 'kehou#home'

  match "/admin" => 'admin#home'

end

app/models/group.rb
# -*- encoding : utf-8 -*-
class Group < ActiveRecord::Base
  attr_accessible :name, :desc, :avatar, :type, :founder_id
  has_attached_file :avatar, :styles => { :medium => "100x100#", :thumb => "54x54#" }, :default_url => 'face.jpg'
  validates_attachment :avatar, :content_type => { :content_type => /image/ }, :size => { :in => 0..2048.kilobytes }

  validates_presence_of :name, :desc

  has_many :members, class_name: "GroupMember", dependent: :destroy, order: 'joined_at desc, created_at desc'
  has_many :invitations, class_name: "GroupMemberInvitation", dependent: :destroy
  has_many :messages, dependent: :destroy, order: 'updated_at DESC'
  has_many :shared_files, dependent: :destroy, order: 'updated_at DESC'
  has_many :assignments, dependent: :destroy, order: 'updated_at DESC', foreign_key: :assigned_group_id, class_name: "Assignment"

  belongs_to :founder, class_name: "User", foreign_key: :founder_id

  validate :name, :length => {:in => 4..30}

end

app/controllers/groups_controller.rb
# -*- encoding : utf-8 -*-
class GroupsController < UserOrientedController
  before_filter :check_group!

  def index
    @groups = current_user.groups
  end

  def show
    @group = current_user.groups.find(params[:id])
    @messages = @group.messages
    @shared_files = @group.shared_files
  end

  def new
    @group = Group.new founder_id: current_user.id
  end

  def create
    @group = Group.new(params[:group])
    @group.founder_id = current_user.id

    @group.members.build role: :founder, user_id: current_user.id, joined_at: Time.now

    if @group.save
      redirect_to groups_path, :notice => "Successfully created teacher/group."
    else
      render :action => 'new'
    end
  end

  def edit
    @group = current_user.groups.find(params[:id])
  end

  def update
    @group = current_user.groups.find(params[:id])
    if @group.update_attributes(params[:group])
      redirect_to @group, :notice  => "Successfully updated teacher/group."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @group = current_user.groups.find(params[:id])
    @group.destroy
    redirect_to groups_path({user_id: current_user.id}), :notice => "Successfully destroyed teacher/group."
  end
end

app/helpers/groups_helper.rb
# -*- encoding : utf-8 -*-
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <input type="button" class="topline_right" value="返回" onclick="window.location='<%= groups_path(user_id: current_user.id) %>';" />
  <div class="space"></div>
  </div>

  <div class="blocks facesetting">
  <div class="block blocksmall">
    <%= image_tag @group.avatar.url(:thumb), class: 'smallface' %>
    <%= image_tag @group.avatar.url, class: 'bigface' %></div>
  <div class="block">
    <div>请选择新的照片文件，文件需小于2MB</div>
    <p>
      <%= f.input :avatar, as: :file, label: false %></p>
    <!-- <p>
      如果你使用的浏览器上传不了头像，请
      <a href="#">点击这里上传</a>
    </p> -->
  </div>
  <p class="space"></p>
  </div>

  <div class="blocks personalsetting">
  <table cellpadding="0" cellspacing="0" border="0" class="normalTable">
    <tr>
      <th width="80">群名称:</th>
      <td>
        <%= f.input :name, label: false, autofocus: true %></td>
    </tr>
    <tr>
      <th>群介绍:</th>
      <td>
        <%= f.input :desc, as: :text, label: false %></td>
    </tr>
  </table>
  <%= f.submit "保存", class: "btn1 btnBig", id:'submit_btn' %>
  <div class='noticebox' id='submit_msg' style='display:none;'>正在保存，如果页面<b>60</b>秒内没有跳转，请<a href='###' onclick='window.location.reload();'>刷新页面</a>。</div>
  <div class="space"></div>
<% end %>


<script type="text/javascript">
$("#submit_btn").on("click", function(){
  $(this).hide();
  $("#submit_msg").show();
})
</script>

app/views/groups/_new_member_form.html.erb
<div class="msgbox" id="addchar" style="width:350px; display:none;">
  <div class="boxcontent">
    <h2>
      添加组员
      <span class="icons closeIcon float_right"></span>
    </h2>
    <%= form_for(GroupMemberVirtualInvitation.new, html: {id: 'invite_member_form'},
      url: group_members_path(user_id: current_user.id), format: :json, remote: true) do |f| %>
      <%= f.hidden_field :group_id, value: @group.id %>
      <table cellpadding="0" cellspacing="0" border="0" class="normalTable">
        <tr>
          <th width="80">学生名字:</th>
          <td>
            <%= f.text_field :child_name%>
          </td>
        </tr>
        <tr>
          <th width="80">学生邮箱:</th>
          <td>
            <%= f.text_field :child_email %>
          </td>
        </tr>
        <tr>
          <th>家长邮箱:</th>
          <td>
            <%= f.text_field :parent_email %>
          </td>
        </tr>
        <tr>
          <th></th>
          <td>
            <%= f.submit "确认提交", class: 'btn btn1' %>
          </td>
        </tr>
      </table>
    <% end %>
  </div>
</div>

app/views/groups/edit.html.erb
<div class="topline topline_with_border">
  <h1>编辑群信息</h1>
  <%= render 'form' %>
</div>

app/views/groups/index.html.erb
<div class="guide_mask"></div>
<div class="guide_steps teacher_grooup_step1">
  <div class="guide_skip_btn"></div>
  <div class="guide_btn">
    <input type="button" class="btn btn1 btnBig" value="创建小组" onclick="window.location='<%= new_group_path %>';" />
  </div>
  <div class="guide_arrow"></div>
  <div class="guide_text">你还没有自己的小组群, 赶紧创建一个吧</div>

  <div class="guide_txt guide_txt1"><h3>1. 创建一个小组</h3></div>
  <div class="guide_txt guide_txt1"><h3>2. 添加小组成员</h3></div>
  <div class="guide_txt guide_txt1"><h3>3. 和小组成员交流</h3><p>在这里, 你可以给他们共享教学资源, 布置作业, 群发消息等等.</p></div>
</div>

<% title "我的小组" %>

<div class="topline topline_with_border">
  <h1>我的小组</h1>
  <% if current_user.usertype == :teacher %>
  <%= button_to "创建小组", new_group_path, class: 'btn btn1 btnBig topline_right',
    method: :get %>
  <% end %>
  <div class="space"></div>
</div>
<div class="blocks groupblocks">
  <% @groups.each do |group| %>
    <div class="block">
      <div class="wrapleft">
        <p>
          <%= link_to group do %>
            <%= image_tag group.avatar.url %>
          <% end %>
        </p>
      </div>
      <div class="wrapright">
        <div class="topline">
          <%= link_to truncate_u(group.name, 30), group, class: 'bigtext' %>
          ( 群成员
          <%= link_to group.members.count, group %>
          )
          <span class="icons viewIcon" onclick="window.location='<%= edit_group_path(group) %>';"></span>
          <div>最近更新 <%= l group.updated_at %></div>
        </div>
        <table cellpadding="0" cellspacing="0" border="0" class="dataTable" style='display:none;'>
          <tr>
            <td width="35">
              <a href="#">
                <%= image_tag "face_2.jpg" %>
              </a>
            </td>
            <td width="120">
              <a href="#">chenjiawei</a>
            </td>
            <td width="70">共享文件</td>
            <td>
              <a href="#">教学平台功能文档.doc</a>
            </td>
          </tr>
          <tr>
            <td width="35">
              <a href="#">
                <img src="../images/face_2.jpg" />
              </a>
            </td>
            <td width="120">
              <a href="#">chenjiawei</a>
            </td>
            <td width="70">发表留言</td>
            <td>
              <a href="#">有人参加明天的活动没?</a>
            </td>
          </tr>
          <tr>
            <td width="35">
              <a href="#">
                <img src="../images/face_2.jpg" />
              </a>
            </td>
            <td width="120">
              <a href="#">chenjiawei</a>
            </td>
            <td width="70">完成作业</td>
            <td>
              <a href="#">初中 阅读理解练习 C1-21, 得分 75.</a>
            </td>
          </tr>
        </table>
      </div>
      <div class="space"></div>
    </div>
  <% end %>
  <div class="space"></div>
</div>


<script>
var list = new Array();
$(document).ready(function(){
  if($(".groupblocks .block").length <= 0)
  {
    set_help_steps();
  }
});
function stepHelp($obj)
{
  this.$obj = $obj;
  this.$mask = $obj.find(".guide_mask");
  this.$step = $obj.find(".guide_steps");
  this.$close = $obj.find(".guide_skip_btn");

  this.init = function(){
    this.$mask.width(this.$obj.width() + parseInt(this.$obj.css("padding-left")) + parseInt(this.$obj.css("padding-right")));
    this.$mask.height(this.$obj.height() + parseInt(this.$obj.css("padding-top")) + parseInt(this.$obj.css("padding-bottom")));
    this.$mask.css({"margin-left": -parseInt(this.$obj.css("padding-left")),
            "margin-top": -parseInt(this.$obj.css("padding-top")), });
    this.$step.width(this.$obj.width());
    this.$step.height(this.$obj.height());
    this.bind_funcs();
  };

  this.show_help = function(){
    this.$mask.show();
    this.$step.show();
  };

  this.hide_help = function(){
    this.$mask.hide();
    this.$step.hide();
  };

  this.bind_funcs = function(){
    var self = this;
    this.$close.bind("click", function(){
      self.hide_help();
    });
  };

  this.init();
  this.show_help();
}
function set_help_steps()
{
  var steps = $(".maincontent");
  for(var a=0; a<steps.length; a++)
  {
    //alert(new stepHelp(steps[a]);
    list.push(new stepHelp($(steps[a])));
  }
}
</script>

app/views/groups/new.html.erb
<div class="topline topline_with_border">
  <h1>创建群信息</h1>
  <%= render 'form' %>
</div>

app/views/groups/show.html.erb
<% title "修改小组信息" %>

<div class="topline topline_with_border">
  <h1>我的小组</h1>
  <%= button_to "返回小组", groups_path({user_id: current_user.id}), class: 'topline_right', method: 'get' %>
  <div class="space"></div>
  </div>
<div class="blocks groupblocks" id="title">
  <div class="block" style="padding-bottom:0px;">
    <div class="wrapleft">
      <p><%= image_tag @group.avatar.url %></p>
    </div>
    <div class="wrapright">
      <div class="topline">
        <%= link_to @group.name, @group, class: 'bigtext' %>
        ( 群成员 <%= link_to @group.members.count, group_path({user_id: current_user.id, id: @group.id}) %> )
        <%= link_to @group, method: :delete, confirm: '确认删除该小组吗？' do %>
          <span class="icons removeIcon"></span>
        <% end %>
        <div>最近更新 <%= l @group.updated_at %></div>
        <div class='group-desc' data-fulldesc="<%= @group.desc %>"><%= truncate_u @group.desc, 240 %>
          <% if realength(@group.desc) > 240 %>
            <a class="group-desc-more-trigger">更多</a></div>
          <% end %>
      </div>
    </div>
  </div>
</div>
<div class="tabs">
  <a href="###" class="on" onclick="show_content(0);">小组成员</a>
  <a href="###" class="" onclick="show_content(1);">小组消息</a>
  <a href="###" class="" onclick="show_content(2);">共享文件</a>
  <div class="space"></div>
</div>

<div class="groups_list">
  <div class="blocks groupbc">
  <% @group.members.students.each do |member| %>
    <div class="block">
      <p>
        <span class="icons charStudentIcon" notice="学生"></span>
        <a href="#" class="face <%= 'actived' if member.joined_at %>">
          <%= image_tag member.joined_at ? "face_2.jpg" : "face.jpg" %>
        </a>
        <span class="name">
          <a href="#"><%= member.name %></a>
          <a href="#"><%= member.user.email %></a>
        </span>
      </p>
      <% parent = member.parent %>
      <% if parent %>
        <p>
          <span class="icons charParentIcon" notice="家长"></span>
          <a href="#" class="face <%= 'actived' if parent.joined_at %>">
            <%= image_tag parent.joined_at ? "face_2.jpg" : "face.jpg" %>
          </a>
          <span class="name">
            <a href="#"><%= parent.name %></a>
            <a href="#"><%= parent.user.email %></a>
          </span>
        </p>
      <% end %>
    </div>
  <% end %>

  <% if current_user.usertype == :teacher %>
  <div class="addBtn">
    <button class="btn1 btnBig addcharbtn">+ 添加组员</button>
  </div>
  <% end %>
</div>

<%= render "new_member_form" %>

<div id="message_div" class="blocks groupblocks" style="display:none;">
  <div class="headerform">
    <%= button_to "发布消息", new_group_message_path(@group), :remote => true, :class => 'btn1 btnBig', method: 'get' %>
  </div>
  <table cellpadding="0" cellspacing="0" border="0" class="dataTable dataTable2">
    <thead>
      <tr>
        <th width="40">头像</th>
        <th width="120"><a href="###">用户名<span class="sicons arrowright"></span></a></th>
        <th width="350"><a href="#">标题<span class="sicons arrowright"></span></a></th>
        <th width="120"><a href="#">发表时间<span class="sicons arrowright"></span></a></th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% @messages.each do |message| %>
      <%= render partial: "/messages/message", locals: { message: message } %>
      <% end %>
    </tbody>
  </table>

  <p class="space"></p>
</div>

<div id="shared_file_div" class="blocks groupblocks" style="display:none;">
  <div class="headerform">
    <%= button_to "上传文件", "/groups/#{@group.id}/shared_files/new", :remote => true, :class => 'btn1 btnBig', method: 'get' %>
  </div>
  <table cellpadding="0" cellspacing="0" border="0" class="dataTable dataTable2">
    <thead>
      <tr>
        <th width="40">头像</th>
        <th width="120"><a href="###">用户名<span class="sicons arrowright"></span></a></th>
        <th width="350"><a href="#">文件名<span class="sicons arrowright"></span></a></th>
        <th width="120"><a href="#">上传时间<span class="sicons arrowright"></span></a></th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% @shared_files.each do |shared| %>
      <%= render partial: "/shared_files/shared_file", locals: { shared_file: shared } %>
      <% end %>
    </tbody>
  </table>
  <p class="space"></p>
</div>
</div>