config/routes.rb
Kehou::Application.routes.draw do
  scope '/users/:user_id/' do
    resources :favorites, shallow: true
    resources :groups, shallow: true do
      resources :messages, shallow: true do
        get :reply, to: 'messages#reply'
      end
      resources :shared_files, shallow: true
    end
    resource :group_members, shallow: true
    resources :assignments, shallow: true do
      get :finished, to: 'assignments#finished_students'
      get :unfinished, to: 'assignments#unfinished_students'
    end

    scope '/assignments/:assignment_id/' do
      resources :assignment_attempts, shallow: true do
        post :post_answer
      end
    end

    get 'assignments/new/choose', :to => 'assignments#choose_practice'

    constraints lambda {|req| User.find(req['user_id']).usertype == :teacher} do
      root :to => "teacher#home", :as => :person_home
      get :home, :to => "teacher#home"
      get :exams, :to => "teacher#exams"
    end

    constraints lambda {|req| User.find(req['user_id']).usertype == :student} do
      root :to => "student#home", :as => :person_home
    end

    constraints lambda {|req| User.find(req['user_id']).usertype == :parent} do
      root :to => "parent#home", :as => :person_home
    end
  end

  resources :profiles

  get "clearsky/index_grade"
  get "clearsky/index_all"
  get "clearsky/landing"
  match '/clearsky/book/:id' => 'clearsky#show_book'
  match '/clearsky/books/:grade' => 'clearsky#show_book_by_grade'
  match "/clearsky/tongbu/:grade/" => 'clearsky#show_tongbu'
  match "/clearsky/tongbu/:grade/:unit" => 'clearsky#do_tongbu'
  match "/clearsky/exam/:id" => 'clearsky#show_practice'
  match "/clearsky/search" => 'clearsky#search'

  match "/explain/displayxml.do" => 'clearsky#displayxml'
  match "/examxml/:id" => 'clearsky#examxml'

  match "/404", :to => "errors#not_found"
  match "/422", :to => "errors#server_error"
  match "/500", :to => "errors#server_error"

  match '/home'  => "kehou#home"
  match '/home2'  => "kehou#home"
  match '/coursewares/:id' => 'kehou#courseware'
  match '/grades/:grade' => 'kehou#grade'
  match '/materials/:id' => 'kehou#material'
  match '/materials/:id/download' => 'kehou#material_download'
  match '/grades/:grade/:category' => 'kehou#grade_category'
  match '/search' => 'kehou#search'
  match '/about' => 'kehou#about'
  match '/comments' => 'kehou#comments'
  match '/contacts' => 'kehou#contacts'
  match '/signed_in_forum' => 'kehou#signed_in_forum'
  match '/logout_redirect' => 'kehou#logout_redirect'

  resources :group_member_invitations do
    collection do
      get :join
      get :regularize
      put :join, to: :active
    end
  end

  scope "/admin" do
    resources :coursewares, :user_type => :admin
  end

  resources :courseware_materials

  match "/update_captcha" => 'simple_captcha#update_captcha'

  get "admin/home"

  get "admin/questions"

  get "admin/exams"

  get "admin/profile"

  devise_for :users, :path => "/", :controllers => { :sessions => "users/sessions", :registrations => "users/registrations" },
    :path_names => {
        :sign_in => 'login',
        :sign_out => 'logout',
        :registration => 'register',
        :sign_up => 'new' }

  devise_for :admins, :path => "/admin", :controllers => { :sessions => "admins/sessions" },
    :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  root :to => 'kehou#home'

  match "/admin" => 'admin#home'

end

app/models/shared_file.rb
# -*- encoding : utf-8 -*-
class SharedFile < ActiveRecord::Base
  attr_accessible :attachment, :description, :tags, :shared_by_id, :group_id
  has_attached_file :attachment

  validates :group_id, :presence => true # 必须在某个群里发消息

  belongs_to :shared_by, class_name: 'User'
  belongs_to :group
end

app/controllers/shared_files_controller.rb
# -*- encoding : utf-8 -*-
class SharedFilesController < ApplicationController
  before_filter :authenticate_user!, :check_group!

  # GET /groups/1/shared_files
  # GET /groups/1/shared_files.json
  def index
    group = Group.find_by_id params[:group_id]
    @shared_files = group.shared_files

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shared_files }
    end
  end

  # GET /groups/1/shared_files/1
  # GET /groups/1/shared_files/1.js
  def show
    @shared_file = SharedFile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.js # show.js.erb
    end
  end

  # GET /groups/1/shared_files/new
  # GET /groups/1/shared_files/new.js
  def new
    @group = Group.find(params[:group_id])
    @shared_file = SharedFile.new
    @shared_file.shared_by_id = current_user.id
    @shared_file.group_id = params[:group_id]

    respond_to do |format|
      format.html # new.html.erb
      format.js # new.js.erb
    end
  end

  # GET /groups/1/shared_files/1/edit
  def edit
    @shared_file = SharedFile.find(params[:id])
  end

  # POST /groups/1/shared_files
  # POST /groups/1/shared_files.js
  def create
    @shared_file = SharedFile.new(params[:shared_file])

    respond_to do |format|
      if @shared_file.save
        format.html { redirect_to url_for(action: :show, group_id: @shared_file.group_id, id: @shared_file.id), notice: '共享文件已经成功上传。' }
        format.js
      else
        format.html { render action: "new" }
        format.js { render action: "new" }
      end
    end
  end

  # PUT /groups/1/shared_files/1
  # PUT /groups/1/shared_files/1.json
  def update
    @shared_file = SharedFile.find(params[:id])

    respond_to do |format|
      if @shared_file.update_attributes(params[:shared_file])
        format.html { redirect_to @shared_file, notice: '共享文件已经成功更新。' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render action: "edit" }
      end
    end
  end

  # DELETE /groups/1/shared_files/1
  # DELETE /groups/1/shared_files/1.js
  def destroy
    @shared_file = SharedFile.find(params[:id])
    @shared_file.destroy

    respond_to do |format|
      format.html { redirect_to shared_files_url }
      format.js
    end
  end
end

app/helpers/shared_files_helper.rb
# -*- encoding : utf-8 -*-
module SharedFilesHelper
  def edit_shared_file_path shared_file
    url_for action: :edit, group_id: shared_file.group_id, id: shared_file.id
  end

  def shared_file_path shared_file, options = {}
    url_for action: :show, group_id: shared_file.group_id, id: shared_file.id
  end
end

app/views/shared_files/_form.html.erb
<div id="new_shared_file_form">
  <div class="boxcontent">
    <h2>
      上传共享文件
    </h2>
    <%= simple_form_for([@group, @shared_file], remote: true) do |f| %>
      <% if @shared_file.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@shared_file.errors.count, "error") %> prohibited this shared_file from being saved:</h2>

          <ul>
          <% @shared_file.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.input :attachment %>
      <%= f.input :description, as: :text, placeholder: '输入描述信息，比如 “这是老师新出的试卷。”' %>

      <%= f.button :submit, "共享" %>

      <%= f.hidden_field :tags %>
      <%= f.hidden_field :shared_by_id %>
      <%= f.hidden_field :group_id %>

    <% end %>
  </div>
</div>

app/views/shared_files/_shared_file.html.erb
<tr id="<%= dom_id shared_file %>">
  <td>
    <% if shared_file.shared_by %>
    <%= link_to (image_tag shared_file.shared_by.final_avatar.url(:original), alt: '头像'), profile_path(shared_file.shared_by), remote: true %>
    <% else %>
    <%= link_to (image_tag 'face.jpg', alt: '头像'), '#' %>
    <% end %>
  </td>
  <td><a href="#">
      <% if shared_file.shared_by %>
      <%= link_to shared_file.shared_by.name, profile_path(shared_file.shared_by), remote: true %>
      <% else %>
      <%= link_to '未知', '#' %>
      <% end %>
  </a></td>
  <td>
    <%= link_to shared_file.attachment_file_name, shared_file.attachment.url %>
  </td>
  <td><%= l shared_file.created_at %></td>
  <td>
    <%= link_to '', shared_file.attachment.url, method: :get, :class=>'icons downloadIcon' %>
    <%= link_to '', "/groups/#{shared_file.group_id}/shared_files/#{shared_file.id}", remote: true, method: :delete, :class=>'icons removeIcon' %>
  </td>
</tr>

app/views/shared_files/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>File:</b>
  <%= @shared_file.attachment_file_name %>
</p>

<p>
  <b>Description:</b>
  <%= @shared_file.description %>
</p>

<p>
  <b>Tags:</b>
  <%= @shared_file.tags %>
</p>

<p>
  <b>Shared by:</b>
  <%= @shared_file.shared_by_id %>
</p>

<p>
  <b>Group:</b>
  <%= @shared_file.group_id %>
</p>

app/views/shared_files/create.js.erb
$("#new_shared_file_form").dialog("close");
$("<%= j render :partial => @shared_file %>").prependTo($("#shared_file_div .dataTable > tbody")).hide().fadeIn();

app/views/shared_files/destroy.js.erb
$("#<%= dom_id @shared_file %>").fadeOut(
    function()
    {
        $(this).remove();
    }
);

app/views/shared_files/edit.html.erb
<h1>Editing shared_file</h1>

<%= render 'form' %>

app/views/shared_files/index.html.erb
<h1>Listing shared_files</h1>

<table>
  <tr>
    <th>Download</th>
    <th>Description</th>
    <th>Tags</th>
    <th>Shared by</th>
    <th>Group</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shared_files.each do |shared_file| %>
  <tr>
    <td><%= link_to shared_file.attachment_file_name, shared_file.attachment.url %></td>
    <td><%= shared_file.description %></td>
    <td><%= shared_file.tags %></td>
    <td><%= shared_file.shared_by_id %></td>
    <td><%= shared_file.group_id %></td>
    <td><%= link_to 'Show', shared_file %></td>
    <td><%= link_to 'Edit', edit_shared_file_path(shared_file) %></td>
    <td><%= link_to 'Destroy', shared_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shared file', new_shared_file_path %>

app/views/shared_files/new.html.erb
<h1>New shared_file</h1>

<%= render 'form' %>

app/views/shared_files/new.js.erb
$("#new_shared_file_form").remove();
$("<%= j render 'form' %>").appendTo($('div:first')).dialog({ width: 640 });

app/views/shared_files/show.html.erb
<%= render "show" %>

app/views/shared_files/show.js.erb
$("#show_shared_file_div").remove();
$("<%= j render 'show' %>").appendTo($(document)).dialog({ width: 640});